- README.md
what : Issue Test
why : Issue Test
Closes #1 
현재 코드
변경 코드
팀원들에게 남길 말
> [feat] : Test Issue

- Backend/src/main/java/com/github/backend/exception/AdminException.java
- Backend/src/main/java/com/github/backend/model/dto/CreateAdmin.java
- Backend/src/main/java/com/github/backend/persist/entity/Admin.java
- Backend/src/main/java/com/github/backend/persist/repository/AdminRepository.java
- Backend/src/main/java/com/github/backend/service/AdminService.java
- Backend/src/main/java/com/github/backend/type/AdminErrorCode.java
- Backend/src/main/java/com/github/backend/web/AdminController.java
- Backend/src/test/java/com/github/backend/admin/controller/AdminControllerTest.java
- Backend/src/test/java/com/github/backend/admin/service/AdminServiceTest.java
Closes #10 
현재 코드
변경 코드
팀원들에게 남길 말
> [feat] Admin 계정 생성 (#10)

- Backend/src/main/java/com/github/backend/exception/CourseException.java
- Backend/src/main/java/com/github/backend/exception/GamerException.java
- Backend/src/main/java/com/github/backend/model/dto/RegisterCourse.java
- Backend/src/main/java/com/github/backend/model/dto/RegisterGamer.java
- Backend/src/main/java/com/github/backend/model/dto/SelectGamer.java
- Backend/src/main/java/com/github/backend/persist/entity/Course.java
- Backend/src/main/java/com/github/backend/persist/entity/Gamer.java
- Backend/src/main/java/com/github/backend/persist/repository/CourseRepository.java
- Backend/src/main/java/com/github/backend/persist/repository/GamerRepository.java
- Backend/src/main/java/com/github/backend/service/CourseService.java
- Backend/src/main/java/com/github/backend/service/GamerService.java
- Backend/src/main/java/com/github/backend/type/CourseErrorCode.java
- Backend/src/main/java/com/github/backend/type/GamerErrorCode.java
- Backend/src/main/java/com/github/backend/web/CourseController.java
- Backend/src/main/java/com/github/backend/web/GamerController.java
- Backend/src/test/java/com/github/backend/admin/controller/CourseControllerTest.java
- Backend/src/test/java/com/github/backend/admin/controller/GamerControllerTest.java
- Backend/src/test/java/com/github/backend/admin/service/CourseServiceTest.java
- Backend/src/test/java/com/github/backend/admin/service/GamerServiceTest.java
Closes #25
강의 등록 기능 
현재 코드
변경 코드
팀원들에게 남길 말
> Backend feat/course register

- Backend/src/main/java/com/github/backend/model/dto/CourseInfoResponse.java
- Backend/src/main/java/com/github/backend/model/dto/UpdateCourse.java
- Backend/src/main/java/com/github/backend/persist/entity/Course.java
- Backend/src/main/java/com/github/backend/persist/entity/Gamer.java
- Backend/src/main/java/com/github/backend/service/CourseService.java
- Backend/src/main/java/com/github/backend/type/CourseErrorCode.java
- Backend/src/main/java/com/github/backend/type/GamerErrorCode.java
- Backend/src/main/java/com/github/backend/web/CourseController.java
- Backend/src/test/java/com/github/backend/admin/controller/CourseControllerTest.java
- Backend/src/test/java/com/github/backend/admin/service/CourseServiceTest.java
Closes #26 
강의 수정 기능을 구현 하였습니다.
현재 코드
변경 코드
팀원들에게 남길 말
> Backend feat/course modify

- Backend/src/main/java/com/github/backend/exception/MemberCourseException.java
- Backend/src/main/java/com/github/backend/persist/entity/Member.java
- Backend/src/main/java/com/github/backend/persist/entity/MemberCourse.java
- Backend/src/main/java/com/github/backend/persist/repository/MemberCourseRepository.java
- Backend/src/main/java/com/github/backend/service/MemberCourseService.java
- Backend/src/main/java/com/github/backend/service/impl/MemberCourseServiceImpl.java
- Backend/src/main/java/com/github/backend/type/MemberCourseErrorCode.java
- Backend/src/test/java/com/github/backend/service/impl/MemberCourseServiceImplTest.java
Closes #24 
회원이 강의를 구매할 수 있는 기능을 구현하였습니다. 
강의 구매 시, 회원이 존재하는지 , 강의가 존재하는지, 회원의 포인트가 강의의 가격보다 많이 남아있는지를 체크 후,
회원의 포인트가 차감되며 강의 구매 내역이 기록됩니다.
현재 코드
변경 코드
수정이 필요한 부분이 있다면 말씀해주세요.
> Backend feat/buy course

- Backend/src/main/java/com/github/backend/persist/entity/MemberCourse.java
- Backend/src/main/java/com/github/backend/persist/repository/MemberCourseRepository.java
- Backend/src/main/java/com/github/backend/service/MemberCourseService.java
- Backend/src/main/java/com/github/backend/service/impl/MemberCourseServiceImpl.java
- Backend/src/main/java/com/github/backend/type/MemberCourseErrorCode.java
- Backend/src/test/java/com/github/backend/service/impl/MemberCourseServiceImplTest.java
Closes #30 
강의 즐겨찾기 기능을 구현했습니다.
toggle 형식으로 서버에서 처리하도록 구현하였습니다.
- bookmark가 true로 되어있을 때, 요청이 들어오면 false로 변경
- bookmark가 false로 되어있을 때, 요청이 들어오면 true로 변경
현재 코드
변경 코드
리뷰 부탁드리겠습니다.
> [feat] 강의 즐겨찾기 기능 구현

- Backend/src/main/java/com/github/backend/model/Result.java
Closes #35 
일관된 응답을 주기 위한 공통 응답 클래스를 작성했습니다.
이전에는 ResponseEntity<Dto>로 응답을 주고 있었습니다.
앞으로는 ResponseEntity<Result<Dto>>를 주면 됩니다.
수정해야 될 부분이 있다면 말씀해주세요.
> [feat] 공통 응답 클래스 추가

- Backend/src/main/java/com/github/backend/security/jwt/JwtAuthenticationFilter.java
- Backend/src/main/java/com/github/backend/security/jwt/JwtAuthenticationProvider.java
- Backend/src/main/java/com/github/backend/security/jwt/JwtEntryPoint.java
- Backend/src/main/java/com/github/backend/security/oauth/OAuth2SuccessHandler.java
- Backend/src/main/java/com/github/backend/service/impl/AttendanceServiceImpl.java
- Backend/src/main/java/com/github/backend/service/impl/CustomOAuth2UserService.java
- Backend/src/main/java/com/github/backend/service/impl/MemberCourseServiceImpl.java
- Backend/src/main/java/com/github/backend/service/impl/TokenService.java
사용하지않는 import 문을 정리하고, 몇 개의 로직을 메소드로 뽑아냈습니다.
현재 코드
변경 코드
팀원들에게 남길 말
> [refactor] auth branch 리팩터링

- Backend/src/main/java/com/github/backend/exception/PostException.java
- Backend/src/main/java/com/github/backend/persist/entity/Post.java
- Backend/src/main/java/com/github/backend/persist/repository/PostRepository.java
- Backend/src/main/java/com/github/backend/service/PostService.java
- Backend/src/main/java/com/github/backend/service/impl/PostServiceImpl.java
- Backend/src/main/java/com/github/backend/type/PostErrorCode.java
- Backend/src/test/java/com/github/backend/service/impl/PostServiceImplTest.java
Closes #37 
현재 코드
변경 코드
팀원들에게 남길 말
> [feat] 게시판 글 작성 기능 구현(#37)

- Backend/src/main/java/com/github/backend/service/AdminService.java
- Backend/src/test/java/com/github/backend/admin/service/AdminServiceTest.java
Closes #48 
현재 코드
변경 코드
팀원들에게 남길 말
> [feat] 게이머 정보 수정 및 삭제

- Backend/src/main/java/com/github/backend/model/dto/AttendanceDto.java
- Backend/src/main/java/com/github/backend/persist/repository/AttendanceRepository.java
- Backend/src/main/java/com/github/backend/service/AttendanceService.java
- Backend/src/main/java/com/github/backend/service/impl/AttendanceServiceImpl.java
- Backend/src/main/java/com/github/backend/web/AttendanceController.java
- Backend/src/test/java/com/github/backend/service/impl/AttendanceServiceImplTest.java
- Backend/src/test/java/com/github/backend/testUtils/WithMemberInfo.java
- Backend/src/test/java/com/github/backend/testUtils/WithMemberInfoSecurityContextFactory.java
- Backend/src/test/java/com/github/backend/web/AttendanceControllerTest.java
Closes #50 
1. 출석 체크 API 작성
2. 출석 조회 API 추가
3. 사용자 인증 정보 모킹을 위한 테스트 유틸 작성
1. 출석 체크 기능(Service)만 있었습니다.
1. 출석 체크 기능을 이용하여 REST API를 작성하였습니다.
2. 출석 조회 API를 추가하였습니다.
3. 사용자 인증 정보를 모킹할 수 있는 테스트 코드를 작성하였습니다.
출석과 관련하여 추가적으로 필요한 기능이 있다던가 코드 중 수정해야할 부분이 있다면 편하게 말씀해주세요!
> [feat] 출석체크 및 조회 API 구현

- Backend/src/main/java/com/github/backend/service/AdminService.java
- Backend/src/main/java/com/github/backend/web/AdminController.java
- Backend/src/test/java/com/github/backend/admin/service/AdminServiceTest.java
- Backend/src/test/java/com/github/backend/web/AdminControllerTest.java
Closes #60 
현재 코드
변경 코드
팀원들에게 남길 말
> [feat] 강의 삭제 기능 추가(#60)

- Backend/build.gradle
- Backend/src/main/java/com/github/backend/exception/MemberException.java
- Backend/src/main/java/com/github/backend/model/dto/MemberInput.java
- Backend/src/main/java/com/github/backend/model/dto/MemberLogout.java
- Backend/src/main/java/com/github/backend/model/dto/ModifyMember.java
- Backend/src/main/java/com/github/backend/model/dto/WithdrawalMember.java
- Backend/src/main/java/com/github/backend/persist/repository/RefreshTokenRepository.java
- Backend/src/main/java/com/github/backend/security/jwt/JwtAuthenticationProvider.java
- Backend/src/main/java/com/github/backend/service/MemberService.java
- Backend/src/main/java/com/github/backend/service/impl/MemberServiceImp.java
- Backend/src/main/java/com/github/backend/type/MemberErrorCode.java
- Backend/src/main/java/com/github/backend/web/MemberController.java
- Backend/src/main/java/com/github/backend/web/TokenController.java
[feat]회원 기능 구현
Closes  #11 #54  
회원탈퇴, 로그아웃, 회원 닉네임 설정 
현재 코드
변경 코드
팀원들에게 남길 말
> [feat]회원 기능 구현

- Backend/src/main/java/com/github/backend/model/dto/UpdateGamer.java
- Backend/src/main/java/com/github/backend/web/AdminController.java
- Backend/src/test/java/com/github/backend/web/AdminControllerTest.java
Closes #62 
Admin 컨트롤러 반환 값 형식 수정 및 테스트 코드 작성하였습니다.
현재 코드
변경 코드
팀원들에게 남길 말
> [feat] Admin 컨트롤러 기능 정리 #62

- Backend/src/main/java/com/github/backend/model/dto/SearchCourse.java
- Backend/src/main/java/com/github/backend/persist/repository/querydsl/CourseSearchRepository.java
- Backend/src/main/java/com/github/backend/persist/repository/querydsl/condition/CourseSearchCondition.java
- Backend/src/main/java/com/github/backend/service/AdminService.java
- Backend/src/main/java/com/github/backend/web/AdminController.java
- Backend/src/test/java/com/github/backend/admin/service/AdminServiceTest.java
- Backend/src/test/java/com/github/backend/web/AdminControllerTest.java
Closes #65 
강의 카테고리(제목, 난이도, 종족) 별 조회 기능 추가
현재 코드
변경 코드
팀원들에게 남길 말
> [feat] Admin 강의 조회 기능 추가 #65

- Backend/src/main/java/com/github/backend/service/AdminService.java
- Backend/src/main/java/com/github/backend/web/AdminController.java
- Backend/src/test/java/com/github/backend/admin/service/AdminServiceTest.java
- Backend/src/test/java/com/github/backend/web/AdminControllerTest.java
Closes #68 
현재 코드
변경 코드
팀원들에게 남길 말
> [feat] 게이머 상세 조회 추가 #68

- frontend/src/components/FreeContent.js
- frontend/src/components/ProGamerCategory.js
- frontend/src/components/ProGamerLecture.js
- frontend/src/pages/ProGamer.js
프로게이머 카테고리 페이지 구현
Closes #73 
프로게이머 카테고리 페이지 구현
현재 코드
변경 코드
팀원들에게 남길 말
> [feat]progamer category

- Backend/src/main/java/com/github/backend/web/common/TokenController.java
- Backend/src/main/java/com/github/backend/web/member/controller/MemberController.java
<Title>
[fix] Controller 리턴 수정과 import 수정
Issue 🎵
Closes https://github.com/Zerobase-Stardy/Stardy/issues/82
Kinds ✅
Feature
Bug Fix
Description ✏
컨트롤러 return값 변경과 병합시 import오류
사용하지않는 import 제거
컨트롤러 return값 통일
import 오류제거
미사용 import 제거
Changes 🛠
AS-IS
현재 코드
TO-BE
변경 코드
Check List 📝
구현 기능 테스트
To Reviewers 🙏
팀원들에게 남길 말
> [fix] Controller 리턴 수정과 import 수정

- Backend/src/main/java/com/github/backend/security/oauth/OAuth2SuccessHandler.java
[fix] 로그인 리다이렉트 수정
what : 로그인 리다이렉트 수정
why : 로그인 후 json형태가아닌 header에 token을 담아 프론트쪽으로 보내주기위해
Closes #88 
로그인 후 json형태가아닌 header에 token을 담아 프론트쪽으로 보내주기위해서 response에서 write하던 값들을 header에 추가해서 프론트쪽으로 넘겨줌
현재 코드
변경 코드
팀원들에게 남길 말
> [fix] 로그인 리다이렉트 수정

- Backend/build.gradle
- Backend/src/main/java/com/github/backend/config/SwaggerConfig.java
- Backend/src/main/java/com/github/backend/dto/attendance/AttendanceDto.java
- Backend/src/main/java/com/github/backend/dto/common/MemberInfo.java
- Backend/src/main/java/com/github/backend/web/member/controller/AttendanceController.java
- Backend/src/main/java/com/github/backend/web/member/controller/MemberController.java
- Backend/src/main/java/com/github/backend/web/myCourse/controller/CourseUnlockController.java
- Backend/src/main/java/com/github/backend/web/myCourse/controller/MyCoursePageController.java
> [build] Swagger 추가

- Backend/src/main/java/com/github/backend/dto/member/MemberSearchOutputDto.java
- Backend/src/main/java/com/github/backend/dto/member/SearchMember.java
- Backend/src/main/java/com/github/backend/dto/member/UpdateMemberNickname.java
- Backend/src/main/java/com/github/backend/persist/member/querydsl/condition/MemberSearchCondition.java
- Backend/src/main/java/com/github/backend/persist/member/repository/MemberSearchRepository.java
- Backend/src/main/java/com/github/backend/service/admin/impl/AdminService.java
- Backend/src/main/java/com/github/backend/web/admin/AdminController.java
- Backend/src/main/java/com/github/backend/web/admin/AdminLoginController.java
- Backend/src/test/java/com/github/backend/admin/service/AdminServiceTest.java
- Backend/src/test/java/com/github/backend/web/AdminControllerTest.java
Closes #103 
admin 회원 조회, 수정 기능입니다.
현재 코드
변경 코드
팀원들에게 남길 말
> [feat]admin 회원 조회, 수정 #103

- Backend/src/main/java/com/github/backend/web/admin/AdminController.java
Closes #106 
현재 코드
변경 코드
팀원들에게 남길 말
> [fix] admin uri 단수 형 => 복수 형 변경(#106)

- Backend/src/main/java/com/github/backend/web/admin/AdminController.java
- Backend/src/main/java/com/github/backend/web/admin/AdminLoginController.java
Closes #108 
admin Swagger 설명 추가
현재 코드
변경 코드
팀원들에게 남길 말
> [feat] admin Swagger 설명 추가

- Backend/src/main/java/com/github/backend/service/course/impl/CourseService.java
- Backend/src/main/java/com/github/backend/web/course/controller/CourseController.java
- Backend/src/test/java/com/github/backend/admin/service/CourseServiceTest.java
- Backend/src/test/java/com/github/backend/web/course/controller/CourseControllerTest.java
Closes #115 
비회원이 강의를 검색할 수 있도록 하였습니다.
현재 코드
변경 코드
팀원들에게 남길 말
> [feat] 비회원 강의 검색

- Backend/src/main/java/com/github/backend/dto/Post/PostListOutPutDto.java
- Backend/src/main/java/com/github/backend/web/post/controller/PostController.java
[fix] 게시판 url수정 + return값 수정
Closes #125 
[fix] 게시판 url수정 + return값 수정
what : 프론트 요청 return 수정
why : api작성법 준수해 uri 수정
현재 코드
단수화 post
변경 코드
복수화 posts 변경
팀원들에게 남길 말
> [fix] 게시판 url수정 + return값 수정

- Backend/src/main/java/com/github/backend/web/post/controller/PostController.java
> [feat] PostController Swagger 추가

- Backend/src/main/java/com/github/backend/dto/Post/SearchTitle.java
- Backend/src/main/java/com/github/backend/persist/post/repository/PostSearchRepository.java
- Backend/src/main/java/com/github/backend/persist/post/repository/querydsl/TitleSearchCondition.java
- Backend/src/main/java/com/github/backend/service/post/PostService.java
- Backend/src/main/java/com/github/backend/service/post/impl/PostServiceImpl.java
- Backend/src/main/java/com/github/backend/web/post/controller/PostController.java
<Title>
[feat] 게시판 페이징 기능
Issue 🎵
// 이번 PR로 특정 이슈를 해결 or 이슈를 닫는다면 # 뒤에 이슈번호를 넣어주세요. 해당 사항이 없다면 지워주시면 됩니다!
Closes #128 
Kinds ✅
Feature
Bug Fix
Description ✏
[feat] 게시판 페이징 기능 추가
what : 게시판 글수에 따른 페이징 기능 추가
why : 전체 게시판 글을 읽어와 처리시 효율성 낮음
Changes 🛠
AS-IS
현재 코드
TO-BE
변경 코드
Check List 📝
구현 기능 테스트
To Reviewers 🙏
팀원들에게 남길 말
> [feat] 게시판 페이징 기능

- Backend/src/main/java/com/github/backend/web/post/controller/PostController.java
게시판 request 수정
Closes #133 
RequestPart는 multipart 형태로 들어와 json 데이터를 읽지 못함
RequestBody형태로 받아와야한다.
현재 코드
@RequestPart 
변경 코드
@RequestBody
팀원들에게 남길 말
> [fix] 게시판 request 수정

- Backend/src/main/java/com/github/backend/dto/attendance/AttendanceDto.java
- Backend/src/main/java/com/github/backend/security/oauth/OAuthService.java
- Backend/src/main/java/com/github/backend/security/oauth/dto/GoogleOAuth2UserInfo.java
- Backend/src/main/java/com/github/backend/security/oauth/dto/OAuth2UserInfoFactory.java
Closes #135 
구글 로그인을 추가했습니다. 
Authorization Code의 Scope 부분은 프론트 엔드와 상의해서 nickname을 받아올 수 있으면 넣고 아니라면 Email의 앞부분을 떼서 닉네임으로 사용하도록 해야합니다! 이부분은 후에 프론트엔드가 구현을 하면 변경하도록 하겠습니다.
현재 코드
변경 코드
이제 거의 막바지입니다 힘냅시다!
> [feat] 구글 로그인 구현

- Backend/src/main/java/com/github/backend/service/post/PostService.java
- Backend/src/main/java/com/github/backend/service/post/impl/PostServiceImpl.java
- Backend/src/main/java/com/github/backend/web/post/controller/PostController.java
[fix] Post member find 수정
[fix] 게시판 request 수정
Closes #이슈 번호
what : 게시판 글 등록시 멤버 데이터를 찾을시 함수 변경
why : findByEmail -> findById가 더 적합
현재 코드
findByEmail
변경 코드
findById
팀원들에게 남길 말
> [fix] Post member find 수정

- Backend/src/main/java/com/github/backend/exception/GlobalExceptionHandler.java
Closes #141 
현재 코드
변경 코드
팀원들에게 남길 말
> [feat] globalException Handler 추가
